Remove code related to cabal-v1
composewell/packcheck pull request #32
Opened 2020-12-13 12:58 UTC by adithyaov

## TODO
- [ ] Manually test the changes

2020-12-13 13:33 UTC, adithyaov commented on packcheck.sh
> +    retry_cmd cabal new-update
`v2-update` here?

2020-12-13 13:35 UTC, adithyaov commented on packcheck.sh
> +  cabal-v1) die "cabal-v1 is not supported, please use cabal-v2 instead";;
`die` here because I don't want to change the behavior, nor do I want to proceed after this point.

2020-12-14 06:11 UTC, harendra-kumar requested changes
Remove `install_cabal_v1_deps` and wherever it is used.
Remove `cabal_v1_configure`.

2020-12-14 06:16 UTC, harendra-kumar commented
Update the README and changelog as well.

2020-12-14 07:07 UTC, adithyaov commented on README.md
> +to your package repo
Oops, I have a hook that removes all trailing spaces on save.

2020-12-17 13:25 UTC, harendra-kumar approved these changes
You can make the suggested changes and merge.

2020-12-17 13:25 UTC, harendra-kumar commented on packcheck.sh
> +      retry_cmd cabal new-update
We can rename it to `cabal v2-update`, `new-update` may go away sooner.

2020-12-17 13:25 UTC, harendra-kumar commented on packcheck.sh
>      run_verbose cabal user-config init || cabal info . > /dev/null || true
1. We can now check cabal version and die if it is older than the one where we have v2 commands.
2. We can remove the `cabal info` command above.

2020-12-17 13:28 UTC, harendra-kumar commented
We can add the github CI files from streamly and transfer the travis tests there.

2020-12-22 01:32 UTC, adithyaov commented
> We can add the gitHub CI files from streamly and transfer the travis tests there.

Will do it in a separate PR.

2020-12-22 01:33 UTC, adithyaov commented
@harendra-kumar Can you please review this again? I'm rather skeptical about bash scripts.

2021-01-01 18:21 UTC, harendra-kumar commented
Looks good.

2021-01-01 20:17 UTC, merged