v0.6.0 release PR
composewell/packcheck pull request #61
Opened 2021-07-16 20:02 UTC by adithyaov

2021-07-16 20:18 UTC, adithyaov commented
See #60 for every CI uncommented.

2021-07-17 18:40 UTC, harendra-kumar requested changes
The README can be updated to mention the github CI support as well.

2021-07-17 18:40 UTC, harendra-kumar commented on .packcheck.ignore
> +appveyor.yml
This is a package for showing example configuration and for CI and it has ready made configs for popular CI platforms. So these files should be packaged in the distribution.

I think we should package all these files and even stack.yaml/cabal.project etc.

2021-07-18 12:55 UTC, harendra-kumar reviewed
1. Regarding the github CI matrix. A CI matrix that multiplies multiple lists is usually fraught with problems. We do not always want to test every dimension crossed with every other dimension. That makes too many tests. And also, if we add one test in one dimension that leads to addition of many tests.
2. Create a v0.6.0 tag and use that tag for PACKCHECK_GITHUB_COMMIT. The config files shipped with the package should have that tag.

2021-07-20 05:53 UTC, harendra-kumar commented
We can replace `cabal-v2` with cabal in the README. Also, the "out of the box support" section in the readme does not mention github.

2021-07-20 06:03 UTC, harendra-kumar commented
It mentions github, I looked at the wrong readme.

2021-07-20 07:13 UTC, harendra-kumar approved these changes

2021-07-20 07:21 UTC, merged